@startwbs CSS history
<style>
   wbsDiagram {
      HorizontalAlignment: left;
      LineColor: black;
      LineThickness: 2
   }
   node {
         HorizontalAlignment: left;
         BackgroundColor: skyblue;
   }
</style>

* CSS History
** 原生CSS
*** CSS 1
**** CSS 1
***** CSS 3
****** CSS 4

** 預處理
*** SASS
**** SCSS
*** LESS
**** Twitter Bootstrap
*** Stylus



** CSS in JS inline-style 
*** styles Components, radium ...etc 共計60餘種

@endwbs
